# Generated by Django 3.2.7 on 2021-12-03 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Name', models.CharField(default='', max_length=300)),
                ('User_Password', models.CharField(default='', max_length=50)),
                ('User_Email', models.CharField(default='', max_length=300)),
                ('User_Address', models.CharField(default='', max_length=300)),
                ('User_District', models.CharField(default='', max_length=20)),
                ('User_Phone', models.CharField(default='', max_length=20)),
                ('User_Type', models.CharField(default='', max_length=20)),
                ('User_Status', models.CharField(default='', max_length=20)),
                ('User_Proof', models.CharField(default='', max_length=20)),
                ('User_Proof_Number', models.CharField(default='', max_length=20)),
                ('other', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
