# Generated by Django 3.2.7 on 2021-12-08 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimeApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_Police',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Plc_Name', models.CharField(default='', max_length=300)),
                ('Plc_District', models.CharField(default='', max_length=300)),
                ('Plc_State', models.CharField(default='', max_length=300)),
                ('Plc_Pin', models.CharField(default='', max_length=300)),
                ('Plc_Number', models.CharField(default='', max_length=300)),
                ('Plc_Email', models.CharField(default='', max_length=300)),
                ('Plc_Password', models.CharField(default='', max_length=300)),
                ('Plc_Type', models.CharField(default='', max_length=300)),
                ('Plc_Image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
