# Generated by Django 3.2.7 on 2021-12-08 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimeApp', '0002_tbl_police'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_Catagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cat_Name', models.CharField(default='', max_length=300)),
            ],
        ),
    ]
