# Generated by Django 3.2.7 on 2021-12-08 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimeApp', '0003_tbl_catagory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_Lawyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lw_Fname', models.CharField(default='', max_length=300)),
                ('Lw_Lname', models.CharField(default='', max_length=300)),
                ('Lw_Image', models.ImageField(upload_to='lawyer/')),
                ('Lw_Phone', models.CharField(default='', max_length=300)),
                ('Lw_Pin', models.CharField(default='', max_length=300)),
                ('Lw_Email', models.CharField(default='', max_length=300)),
                ('Lw_Pswd', models.CharField(default='', max_length=300)),
                ('Lw_Address', models.CharField(default='', max_length=300)),
                ('Lw_State', models.CharField(default='', max_length=300)),
                ('Lw_District', models.CharField(default='', max_length=300)),
                ('Lw_Proof', models.CharField(default='', max_length=300)),
                ('Lw_ProofNo', models.CharField(default='', max_length=300)),
                ('Lw_Status', models.CharField(default='', max_length=300)),
                ('Lw_EnrollNo', models.CharField(default='', max_length=300)),
            ],
        ),
    ]
