# Generated by Django 3.2.7 on 2021-12-08 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimeApp', '0004_tbl_lawyer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_user',
            old_name='other',
            new_name='User_State',
        ),
        migrations.AddField(
            model_name='tbl_user',
            name='User_Image',
            field=models.ImageField(default='', upload_to='user/'),
        ),
    ]
