# Generated by Django 3.2.7 on 2021-12-08 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crimeApp', '0005_auto_20211208_1626'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_user',
            old_name='User_Status',
            new_name='User_PIN',
        ),
    ]
