# Generated by Django 3.2.7 on 2021-12-10 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crimeApp', '0006_rename_user_status_tbl_user_user_pin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('police_station_name', models.CharField(default='', max_length=300)),
                ('petitioner_name', models.CharField(default='', max_length=300)),
                ('petitioner_id', models.CharField(default='', max_length=300)),
                ('petitioner_id_no', models.CharField(default='', max_length=300)),
                ('petitioner_phone', models.CharField(default='', max_length=300)),
                ('petitioner_email', models.CharField(default='', max_length=300)),
                ('petitioner_address', models.CharField(default='', max_length=300)),
                ('date_of_issue', models.CharField(default='', max_length=300)),
                ('subject', models.CharField(default='', max_length=300)),
                ('description', models.CharField(default='', max_length=300)),
                ('pic_complaint', models.ImageField(upload_to='complaint/')),
                ('lawyer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crimeApp.tbl_lawyer')),
                ('police_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crimeApp.tbl_police')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crimeApp.tbl_user')),
            ],
        ),
    ]
