# Generated by Django 3.2.7 on 2021-12-10 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimeApp', '0007_tbl_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_complaint',
            name='petitioner_district',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='tbl_complaint',
            name='petitioner_pin',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='tbl_complaint',
            name='petitioner_state',
            field=models.CharField(default='', max_length=300),
        ),
    ]
