# Generated by Django 3.2.7 on 2021-12-10 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crimeApp', '0008_auto_20211210_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_complaint',
            name='lawyer_id',
        ),
    ]
