# Generated by Django 3.2.7 on 2021-12-10 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimeApp', '0009_remove_tbl_complaint_lawyer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_lawyer',
            name='Lw_Catgry',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='tbl_lawyer',
            name='Lw_Fees',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='tbl_lawyer',
            name='Lw_Time',
            field=models.CharField(default='', max_length=300),
        ),
    ]
