# Generated by Django 3.2.7 on 2021-12-10 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crimeApp', '0010_auto_20211210_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default='', max_length=30)),
                ('time', models.CharField(default='', max_length=30)),
                ('status', models.CharField(default='', max_length=30)),
                ('link', models.CharField(default='', max_length=30)),
                ('lawyer_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crimeApp.tbl_lawyer')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crimeApp.tbl_user')),
            ],
        ),
    ]
