# Generated by Django 3.2.7 on 2021-12-10 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimeApp', '0011_tbl_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_booking',
            name='apply_date',
            field=models.CharField(default='', max_length=30),
        ),
    ]
