# Generated by Django 3.2.7 on 2021-12-11 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimeApp', '0012_tbl_booking_apply_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_booking',
            name='link',
            field=models.CharField(default='', max_length=300),
        ),
    ]
