# Generated by Django 3.2.7 on 2021-12-11 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crimeApp', '0013_alter_tbl_booking_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('email', models.CharField(default='', max_length=30)),
                ('message', models.CharField(default='', max_length=30)),
                ('lawyer_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crimeApp.tbl_lawyer')),
                ('police_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crimeApp.tbl_police')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crimeApp.tbl_user')),
            ],
        ),
    ]
