# Generated by Django 3.2.7 on 2021-12-11 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimeApp', '0014_tbl_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_feedback',
            name='lawyer_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='tbl_feedback',
            name='station_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='tbl_feedback',
            name='user_name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
