# Generated by Django 3.2.7 on 2021-12-11 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimeApp', '0015_auto_20211211_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_complaint',
            name='status',
            field=models.CharField(default='', max_length=300),
        ),
    ]
