# Generated by Django 3.2.7 on 2021-12-13 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crimeApp', '0016_tbl_complaint_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_FIR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fir_number', models.CharField(default='', max_length=30)),
                ('fir_off_name', models.CharField(default='', max_length=30)),
                ('fir_date', models.CharField(default='', max_length=30)),
                ('fir_evidence', models.CharField(default='', max_length=30)),
                ('fir_findings', models.CharField(default='', max_length=30)),
                ('fir_pic', models.ImageField(upload_to='FIR/')),
                ('complaint_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crimeApp.tbl_complaint')),
                ('police_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crimeApp.tbl_police')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crimeApp.tbl_user')),
            ],
        ),
    ]
