# Generated by Django 3.2.7 on 2021-12-13 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimeApp', '0017_tbl_fir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_fir',
            name='fir_evidence',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='tbl_fir',
            name='fir_findings',
            field=models.CharField(default='', max_length=300),
        ),
    ]
